# ---- Build stage ----
FROM golang:alpine AS builder
ARG GIT_COMMIT
ARG GO_BUILD_TAGS
WORKDIR /src
# Copy source
COPY ./src .

# Build static binary
RUN CGO_ENABLED=0 GOOS=linux go build -tags "${GO_BUILD_TAGS}" -trimpath -ldflags="-s -w -X main.gBuildPlatform=alpine" -o /tmp/smtproxy

# ---- Runtime image ----

FROM alpine

RUN apk add --no-cache ca-certificates libcap

# Copy binary
COPY --from=builder /tmp/smtproxy /usr/local/bin/smtproxy

# Allow to bind to ports below 1024
RUN setcap 'cap_net_bind_service=+ep' /usr/local/bin/smtproxy && mkdir /tls && chown 1000 /tls

USER 1000
EXPOSE 25 465 1025 1465

ENTRYPOINT ["/usr/local/bin/smtproxy"]
