# ---- Build stage ----

FROM cgr.dev/chainguard/go:latest AS builder
ARG GIT_COMMIT
WORKDIR /src
COPY ./src .
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w -X main.gBuildPlatform=static" -o /tmp/smtproxy

# ---- Capability stage ----

FROM cgr.dev/chainguard/wolfi-base AS cap
RUN apk add --no-cache libcap libcap-utils
COPY --from=builder /tmp/smtproxy /usr/local/bin/smtproxy
RUN setcap cap_net_bind_service=+ep /usr/local/bin/smtproxy

# Optional verification
RUN getcap /usr/local/bin/smtproxy

# ---- Runtime stage ----

FROM cgr.dev/chainguard/static:latest
# copy the already-prepared file
COPY --from=cap /usr/local/bin/smtproxy /usr/local/bin/smtproxy
COPY --chown=nonroot:nonroot --from=builder /dev/null /tls/.keep

USER nonroot
EXPOSE 25 465 1025 1465
ENTRYPOINT ["/usr/local/bin/smtproxy"]
