worker_processes  1;

events {
    worker_connections 1024;
}

stream {

    upstream backend_proxy {
        server 127.0.0.1:1025;
    }

    server {
        listen 2500;
        proxy_pass backend_proxy;
        proxy_protocol on;
    }

}
